### ISSUE TITLE
Latest version of Node that works with this? 

### ISSUE THREAD

**Issue by ckshei** [sampl/firefly#174]
What verison of Node should I use with this? Ran the code with version 12 and had some difficulties installing a few npm packages

**Comment by sampl** [comment]
Shoot, not sure why it wouldn’t handle it. Did you try a more recent
version of node? Would you mind sharing the errors?

**Comment by jambrose42** [comment]
```
> grpc@1.9.1 install /Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.9.1/node-v64-darwin-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.9.1 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.9.1/node-v64-darwin-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.9.1 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
gypgyp  ERR!ERR!  configure errorconfigure error

gypgyp  ERR!ERR!  stackstack Error: EACCES: permission denied, mkdir '/Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc/build'
 Error: EACCES: permission denied, mkdir '/Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc/build'
gypgyp  ERR!ERR!  System Darwin 19.3.0
System Darwin 19.3.0
gypgyp  ERR!ERR!  commandcommand "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown"
 "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown"
gypgyp  ERR!ERR!  cwdcwd /Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc
 /Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc
gypgyp  ERR!ERR!  node -vnode -v v10.15.3
 v10.15.3
gypgyp  ERR!ERR!  node-gyp -vnode-gyp -v v3.8.0
 v3.8.0
gyp ERR! gypnot ok
 ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 19.3.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Library/WebServer/Documents/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown' (1)
npm WARN firefly-scripts@1.0.0 No repository field.
npm WARN firefly-scripts@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.9.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.9.1 install script.
```

**Comment by mtompkins** [comment]
Fails on v13.
Looks like it may be limited to Node v10 https://github.com/nodejs/node-gyp/issues/2025#

**Comment by tamlyn** [comment]
No joy on Node 14 either. Seems to be a known issue with `grpc` https://github.com/grpc/grpc-node/issues/922
