### ISSUE TITLE
Errors during npm i

### ISSUE THREAD

**Issue by dzoba** [sampl/firefly#187]
Thanks for making such a wonderful project!  I was trying to use it today but was getting errors during install.  I thought it might be an issue with Big Sur so I created an Ubuntu VM and was getting the same thing.  

![image](https://user-images.githubusercontent.com/857664/100518466-a253ff00-315f-11eb-9663-8d08f1aaaced.png)

`parallels@parallels-Parallels-Virtual-Platform:~/firefly/scripts$ npm i

> grpc@1.9.1 install /home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.9.1/node-v83-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.9.1 and node@14.15.1 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.9.1/node-v83-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.9.1 and node@14.15.1 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
make: Entering directory '/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
rm: cannot remove './Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw': No such file or directory
grpc.target.mk:409: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o' failed
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
make: Leaving directory '/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/parallels/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/home/parallels/.nvm/versions/node/v14.15.1/bin/node" "/home/parallels/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc"
gyp ERR! cwd /home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/parallels/.nvm/versions/node/v14.15.1/bin/node /home/parallels/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 4.15.0-34-generic
node-pre-gyp ERR! command "/home/parallels/.nvm/versions/node/v14.15.1/bin/node" "/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc
node-pre-gyp ERR! node -v v14.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/home/parallels/.nvm/versions/node/v14.15.1/bin/node /home/parallels/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc' (1)
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.onstall script
../deps/grpc/src/core/lib/channel/channel_args.cc:499:1: fatal error: opening dependency file ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o.d.raw: No such file or directory
 }
 ^
compilation terminated.
grpc.target.mk:409: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o' failed
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o] Error 1
make: Leaving directory '/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/parallels/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/home/parallels/.nvm/versions/node/v14.15.1/bin/node" "/home/parallels/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc"
gyp ERR! cwd /home/parallels/firefly/scripts/node_modules/google-gax/node_modules/grpc
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN firefly-scripts@1.0.0 No repository field.
npm WARN firefly-scripts@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.9.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.9.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/parallels/.npm/_logs/2020-11-28T14_47_58_818Z-debug.log
`

**Comment by sampl** [comment]
Hi @dzoba thanks for the issue report :)

So sorry about that, I'm guessing this is long overdue for an npm package upgrade. I'm not maintaining this a lot right now but I'll try to circle back when I can!

**Comment by dzoba** [comment]
Thanks @sampl !  The concept behind this boiler plate is amazing!  Sorry to hear about it not being maintained
